[project]
name = "antigravity-mcp-csv-add-deduplicate"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp>=1.26.0",
    "pandas>=3.0.1",
]
